name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        path: head

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install times-excel-reader
      run: |
        pip install -U pip
        pip install git+https://github.com/etsap-TIMES/times-excel-reader.git@0f7793abf2d28c8aec83e90446a16d0f0ce98893

    - name: Run raw_table_summary on TIMES-NZ-Model-Files
      run: |
        times-excel-reader head/TIMES-NZ/ --output_dir head/TIMES-NZ/raw_table_summary/ --only_read

    - name: Check if raw_table_summary is updated
      id: raw_table_updated
      run: |
        cd head/TIMES-NZ/raw_table_summary
        if ! git diff --quiet; then \
          echo "ERROR: raw_table_summary is not up-to-date."; \
          echo "The uploaded artifact contains the raw_table_summary for your branch, commit that to pass this check."; \
          echo "See README for more details."; \
          exit 1; fi

    - name: Upload raw_tables.txt
      uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.raw_table_updated.outcome == 'failure' }}
      with:
        name: raw_tables
        path: head/TIMES-NZ/raw_table_summary/raw_tables.txt

    - name: Run times-excel-reader on TIMES-NZ-Model-Files
      run: |
        echo "Temporarily disabled. See https://github.com/EECA-NZ/TIMES-NZ-Model-Files/issue/10"
        # times-excel-reader ../model # CURRENTLY BROKEN
